CREATE KEYSPACE offers
WITH REPLICATION = {
'class' : 'SimpleStrategy',
'replication_factor' : 1
}
;
CREATE TABLE offers.offers
(shopname varchar,
 shopcompany varchar,
 shopurl varchar,
 shopcategories list<text>,
 id int,
 type varchar,
 available varchar,
 bid varchar,
 cbid varchar,
 fee varchar,
 group_id int,
 url varchar,
 price int,
 oldprice int,
 currencyid varchar,
 categoryid int,
 picture varchar,
 store boolean,
 pickup boolean,
 delivery boolean,
 name varchar,
 vendor varchar,
 vendorcode varchar,
 description varchar,
 sales_notes varchar,
 manufacturer_warranty boolean,
 country_of_origin varchar,
 barcode varchar,
 typeprefix varchar,
 model varchar,
 adult boolean,
 expiry varchar,
 weight varchar,
 dimensions varchar,
 conditiontype varchar,
 conditionreason list<text>,
 deliveryoptions list<text>,
 shipmentoptions list<text>,
 ageunit varchar,
 age varchar,
 param list<text>,
 PRIMARY KEY (shopname, id))